export const SAMPLE_DATA = [
  {
    id: 1,
    step: 'OT',
    list: [
      {
        id: 1,
        name: '김유진',
        firstDate: '2023-04-30',
        birthDate: '1989-12-28',
        isBaptized: true,
        address: '주안동 18-5 2층',
        phoneNumber: '010-8589-0530',
        guide: '',
        job: '반도체 개발 연구원',
        note: '장기결석자, 모태신앙',
        responsibility: '지원석',
        team: '',
        attendance: {
          orientation: '2023-04-30',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 2,
        name: '김진헌',
        firstDate: '2023-03-26',
        birthDate: '2001-06-09',
        isBaptized: true,
        address: '인천시 미추홀구 용현동',
        phoneNumber: '010-9748-8294',
        guide: '자진',
        job: '취준생(건축설계사)',
        note: '예전에 주안감리교회를 다녔음',
        responsibility: '임선우',
        team: '',
        attendance: {
          orientation: '2023-03-26',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 8,
        name: '유수호',
        firstDate: '2023-03-26',
        birthDate: '2003-10-31',
        isBaptized: true,
        address: '용현동',
        phoneNumber: '010-4425-4946',
        guide: '전도(신혜원)',
        job: '학생(인하대 전기공학과)',
        note: '',
        responsibility: '황종우',
        team: '',
        attendance: {
          orientation: '2023-03-26',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 9,
        name: '신혜원',
        firstDate: '2023-02-26',
        birthDate: '2004-05-22',
        isBaptized: true,
        address: '미추홀구 용현동',
        phoneNumber: '010-7197-8365',
        guide: '자진 출석',
        job: '학생(아태물류학과)',
        note: '찬양팀 사역, 취미: 춤, 남자친구와 함께 교육 수강 희망',
        responsibility: '임선우',
        team: '',
        attendance: {
          orientation: '2023-02-26',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 10,
        name: '이승호',
        firstDate: '2023-04-23',
        birthDate: '2004-04-07',
        isBaptized: true,
        address: '경기도 화성시 봉담읍 와우리 43-42',
        phoneNumber: '010-7274-7503',
        guide: '신혜원',
        job: '대학생(건강관리운동학과)',
        note: '',
        responsibility: '황종우',
        team: '',
        attendance: {
          orientation: '2023-04-23',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 11,
        name: '문준호',
        firstDate: '2023-04-30',
        birthDate: '2002-01-21',
        isBaptized: true,
        address: '인천시 미추홀구 주안동 77-3 지웰에스테이트',
        phoneNumber: '010-8407-1677',
        guide: '어머님 소개',
        job: '학생(체육학과)',
        note: '',
        responsibility: '임선우',
        team: '',
        attendance: {
          orientation: '2023-05-07',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 12,
        name: '황정택',
        firstDate: '2023-04-30',
        birthDate: '1994-05-12',
        isBaptized: false,
        address: '주안동 3-26',
        phoneNumber: '010-4457-0984',
        guide: '자진',
        job: '요식업 폐업 후 스타트업 준비 중',
        note: '한 달 정도 교회 경험 있음',
        responsibility: '지원석',
        team: '',
        attendance: {
          orientation: '2023-04-30',
          first: '',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
    ],
  },
  {
    id: 2,
    step: '1주차',
    list: [
      {
        id: 3,
        name: '최은진',
        firstDate: '2023-04-16',
        birthDate: '1994-05-07',
        isBaptized: true,
        address: '인천시 남동구 백범로 294번길 16',
        phoneNumber: '010-5104-6635',
        guide: '자진',
        job: '직장인 - 사무직',
        note: '이경재 간사님과 직장 동료',
        responsibility: '전하은',
        team: '',
        attendance: {
          orientation: '2023-04-16',
          first: '2023-04-30',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 4,
        name: '황상훈',
        firstDate: '2023-04-16',
        birthDate: '2001-01-18',
        isBaptized: false,
        address: '',
        phoneNumber: '010-7513-9855',
        guide: '자진',
        job: '대학생 (정보통신)',
        note: '집중이 필요',
        responsibility: '임선우',
        team: '',
        attendance: {
          orientation: '2023-04-16',
          first: '2023-04-30',
          second: '',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
    ],
  },
  {
    id: 3,
    step: '2주차',
    list: [
      {
        id: 5,
        name: '이진호',
        firstDate: '2023-04-09',
        birthDate: '1992-08-15',
        isBaptized: false,
        address: '인천시 미추홀구 미추홀대로 632번길 71',
        phoneNumber: '010-4922-7065',
        guide: '박찬숙 간사님',
        job: '',
        note: '',
        responsibility: '전하은',
        team: '',
        attendance: {
          orientation: '2023-04-16',
          first: '2023-04-23',
          second: '2023-04-30',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 6,
        name: '이승민',
        firstDate: '2023-04-16',
        birthDate: '2001-02-18',
        isBaptized: false,
        address: '인천시 미추홀구 용현동 신창아파트',
        phoneNumber: '010-3309-4054',
        guide: '유영은 간사님',
        job: '취준생(바리스타 전공)',
        note: '하나님의 교회, 대순진리회 경험, 교회에 대한 궁금증 많음',
        responsibility: '지원석',
        team: '',
        attendance: {
          orientation: '2023-04-16',
          first: '2023-04-23',
          second: '2023-04-30',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
      {
        id: 7,
        name: '김성욱',
        firstDate: '2023-04-16',
        birthDate: '2004-02-11',
        isBaptized: false,
        address: '',
        phoneNumber: '010-5736-5984',
        guide: '자진(어머니랑 같이 교회 옴)',
        job: '',
        note: '',
        responsibility: '황종우',
        team: '',
        attendance: {
          orientation: '2023-04-16',
          first: '2023-04-23',
          second: '2023-04-30',
          third: '',
          fourth: '',
          isCompleted: false,
        },
        memo: [],
      },
    ],
  },
  {
    id: 4,
    step: '3주차',
    list: [],
  },
  {
    id: 5,
    step: '4주차',
    list: [],
  },
  {
    id: 6,
    step: '등반',
    list: [],
  },
];
