export const VILLAGE_DATA = [
  {
    id: 1,
    village: 1,
    elder: ["백안선"],
    pastures: [
      {
        id: 1,
        pastureNumber: 1,
        list: [
          {
            id: 1,
            name: "서재정",
            position: "leader",
            gender: "male",
            birthYear: 1995,
          },
          {
            id: 2,
            name: "편무현",
            position: "sheep",
            gender: "male",
            birthYear: 1991,
          },
          {
            id: 3,
            name: "장진실",
            position: "sheep",
            gender: "female",
            birthYear: 1991,
          },
          {
            id: 4,
            name: "한송이",
            position: "sheep",
            gender: "female",
            birthYear: 1991,
          },
          {
            id: 5,
            name: "장해빈",
            position: "sheep",
            gender: "male",
            birthYear: 1994,
          },
          {
            id: 6,
            name: "엄태완",
            position: "sheep",
            gender: "male",
            birthYear: 1997,
          },
          {
            id: 7,
            name: "이용준",
            position: "sheep",
            gender: "male",
            birthYear: 1998,
          },
          {
            id: 8,
            name: "전유라",
            position: "sheep",
            gender: "male",
            birthYear: 1998,
          },
          {
            id: 9,
            name: "고성현",
            position: "sheep",
            gender: "male",
            birthYear: 1999,
          },
          {
            id: 10,
            name: "김재은",
            position: "sheep",
            gender: "female",
            birthYear: 1999,
          },
          {
            id: 11,
            name: "이석규",
            position: "sheep",
            gender: "male",
            birthYear: 1999,
          },
          {
            id: 12,
            name: "송승훈",
            position: "sheep",
            gender: "male",
            birthYear: 2000,
          },
          {
            id: 13,
            name: "전유정",
            position: "sheep",
            gender: "female",
            birthYear: 2000,
          },
          {
            id: 14,
            name: "오민영",
            position: "sheep",
            gender: "female",
            birthYear: 2001,
          },
          {
            id: 15,
            name: "이명하",
            position: "sheep",
            gender: "female",
            birthYear: 2000,
          },
          {
            id: 16,
            name: "김나윤",
            position: "sheep",
            gender: "female",
            birthYear: 1997,
          },
        ],
      },
      {
        id: 2,
        pastureNumber: 2,
        list: [
          {
            id: 1,
            name: "엄현지",
            position: "leader",
            gender: "female",
            birthYear: 1995,
          },
          {
            id: 2,
            name: "김요셉",
            position: "sheep",
            gender: "male",
            birthYear: 2001,
          },
          {
            id: 3,
            name: "이은서",
            position: "sheep",
            gender: "female",
            birthYear: 2002,
          },
          {
            id: 4,
            name: "권세인",
            position: "sheep",
            gender: "female",
            birthYear: 2002,
          },
          {
            id: 5,
            name: "권정욱",
            position: "sheep",
            gender: "female",
            birthYear: 2002,
          },
          {
            id: 6,
            name: "엄하영",
            position: "sheep",
            gender: "male",
            birthYear: 2002,
          },
          {
            id: 7,
            name: "오혜인",
            position: "sheep",
            gender: "female",
            birthYear: 2002,
          },
          {
            id: 8,
            name: "윤준혁",
            position: "sheep",
            gender: "male",
            birthYear: 2002,
          },
          {
            id: 9,
            name: "김진하",
            position: "sheep",
            gender: "male",
            birthYear: 2003,
          },
          {
            id: 10,
            name: "이슬아",
            position: "sheep",
            gender: "female",
            birthYear: 2003,
          },
          {
            id: 11,
            name: "최효은",
            position: "sheep",
            gender: "female",
            birthYear: 2003,
          },
          {
            id: 12,
            name: "이규헌",
            position: "sheep",
            gender: "male",
            birthYear: 2004,
          },
          {
            id: 13,
            name: "이윤서",
            position: "sheep",
            gender: "male",
            birthYear: 2004,
          },
          {
            id: 14,
            name: "정유빈",
            position: "sheep",
            gender: "female",
            birthYear: 2004,
          },
          {
            id: 15,
            name: "최인서",
            position: "sheep",
            gender: "female",
            birthYear: 2004,
          },
          {
            id: 16,
            name: "최인서",
            position: "sheep",
            gender: "female",
            birthYear: 2004,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    village: 2,
    elder: ["박찬숙", "이경재"],
    pastures: [
      {
        id: 1,
        pastureNumber: 3,
        list: [
          {
            id: 1,
            name: "장민우",
            position: "leader",
            gender: "male",
            birthYear: 1987,
          },
          {
            id: 2,
            name: "장경화",
            position: "vice-leader",
            gender: "female",
            birthYear: 1996,
          },
          {
            id: 3,
            name: "윤성현",
            position: "sheep",
            gender: "female",
            birthYear: 1984,
          },
          {
            id: 4,
            name: "신현수",
            position: "sheep",
            gender: "male",
            birthYear: 1985,
          },
          {
            id: 5,
            name: "최배창",
            position: "sheep",
            gender: "male",
            birthYear: 1985,
          },
          {
            id: 6,
            name: "박인상",
            position: "sheep",
            gender: "male",
            birthYear: 1987,
          },
          {
            id: 7,
            name: "장민오",
            position: "sheep",
            gender: "male",
            birthYear: 1987,
          },
          {
            id: 8,
            name: "장해미",
            position: "sheep",
            gender: "female",
            birthYear: 1988,
          },
          {
            id: 9,
            name: "박진우",
            position: "sheep",
            gender: "male",
            birthYear: 1991,
          },
          {
            id: 10,
            name: "김유정",
            position: "sheep",
            gender: "female",
            birthYear: 1992,
          },
          {
            id: 11,
            name: "이예섭",
            position: "sheep",
            gender: "male",
            birthYear: 1994,
          },
          {
            id: 12,
            name: "이은혜",
            position: "sheep",
            gender: "female",
            birthYear: 1994,
          },
          {
            id: 13,
            name: "신덕유",
            position: "sheep",
            gender: "male",
            birthYear: 1995,
          },
          {
            id: 14,
            name: "임다솔",
            position: "sheep",
            gender: "female",
            birthYear: 1996,
          },
          {
            id: 15,
            name: "권정민",
            position: "sheep",
            gender: "female",
            birthYear: 1996,
          },
          {
            id: 16,
            name: "김동호",
            position: "sheep",
            gender: "male",
            birthYear: 1998,
          },
        ],
      },
      {
        id: 2,
        pastureNumber: 4,
        list: [
          {
            id: 1,
            name: "황영곤",
            position: "leader",
            gender: "male",
            birthYear: 1991,
          },
          {
            id: 2,
            name: "박주영",
            position: "vice leader",
            gender: "male",
            birthYear: 1997,
          },
          {
            id: 3,
            name: "백승환",
            position: "sheep",
            gender: "male",
            birthYear: 1991,
          },
          {
            id: 4,
            name: "배종윤",
            position: "sheep",
            gender: "male",
            birthYear: 1992,
          },
          {
            id: 5,
            name: "전성호",
            position: "sheep",
            gender: "male",
            birthYear: 1993,
          },
          {
            id: 6,
            name: "김세현",
            position: "sheep",
            gender: "male",
            birthYear: 1995,
          },
          {
            id: 7,
            name: "강제현",
            position: "sheep",
            gender: "male",
            birthYear: 1995,
          },
          {
            id: 8,
            name: "윤예지",
            position: "sheep",
            gender: "female",
            birthYear: 1995,
          },
          {
            id: 9,
            name: "이지윤",
            position: "sheep",
            gender: "female",
            birthYear: 1995,
          },
          {
            id: 10,
            name: "오혜린",
            position: "sheep",
            gender: "female",
            birthYear: 1996,
          },
          {
            id: 11,
            name: "정예헌",
            position: "sheep",
            gender: "female",
            birthYear: 1996,
          },
          {
            id: 12,
            name: "권윤",
            position: "sheep",
            gender: "male",
            birthYear: 1997,
          },
          {
            id: 13,
            name: "김연진",
            position: "sheep",
            gender: "male",
            birthYear: 1999,
          },
          {
            id: 14,
            name: "이진석",
            position: "sheep",
            gender: "male",
            birthYear: 1997,
          },
          {
            id: 15,
            name: "허윤",
            position: "sheep",
            gender: "male",
            birthYear: 1999,
          },
          {
            id: 16,
            name: "윤병훈",
            position: "sheep",
            gender: "male",
            birthYear: 2000,
          },
          {
            id: 17,
            name: "박현민",
            position: "sheep",
            gender: "male",
            birthYear: 2001,
          },
          {
            id: 18,
            name: "복진배",
            position: "sheep",
            gender: "male",
            birthYear: 1991,
          },
        ],
      },
    ],
  },
];
